### ISSUE TITLE
ÜSTRA Fahrplan

### ISSUE THREAD

**Issue by elektrojenny** [ArduinoHannover/DBAPI#1]
Hallo,
gibt es auch eine Schnittstelle für die Üstra/GVH?
Gruss aus Hannover
Frank J

**Comment by soundstorm** [comment]
Hallo Frank,
einfach bei der Anfrage `PROD_BUS | PROD_STB` benutzen und eine entsprechende Haltestelle des GVH anfragen, dann gibt es den Nahverkehr. Ansonsten habe ich für den GVH keine separate Ansteuerung, sondern auch nur über die Bahn API. Verspätungen sind nicht immer verfügbar.
Beste Grüße zurück

**Comment by miruthde** [comment]
Sehr cool, bin grad dabei einen Automatismus für die GVH Garantie Anträge zu bauen. Wird groß.
