### ISSUE TITLE
No Data Stream

### ISSUE THREAD

**Issue by SEB224** [ArduinoHannover/DBAPI#3]
Hallo,
hat sich die API der DB zum neuen Jahr geändert?
Ich bekomme seit 2021 keine Daten mehr.
Verbindung zum Netz besteht. 

Danke und Grüße,
Seb

**Comment by soundstorm** [comment]
Hi @SEB224,
nach wie vor läuft die API bei mir und liefert Daten. Sonst irgendetwas verändert? Funktioniert der Beispielcode? Sonst irgendetwas verändert?
Beste Grüße

**Comment by SEB224** [comment]
Hallo nochmal, 

danke für die Info. Ich habe jetzt nochmal alle Bibliotheken neu installiert und es geht wieder.

viele Grüße
