### ISSUE TITLE
negativer Delay

### ISSUE THREAD

**Issue by quotschmacher** [ArduinoHannover/DBAPI#4]
Ist uint16_t für den delay nicht ein etwas unglückliches Format? Wie wird denn da ein negativer delay gehandhabt? Laut der Beschreibung von "textdelay" kann der ja auch durchaus negativ sein. Oder wird da intern in den Funktionen gecastet? Das würde aber dennoch zu einem falschen Wert führen, wenn man selber Berechnungen mit "delay" machen möchte.

**Comment by soundstorm** [comment]
Ist jetzt int16_t, aber prüfe gerade noch, wie die API eine Verfrühung ausgibt, solche Fälle sind ja doch eher rar.
