### ISSUE TITLE
Target variable in getStationBoard

### ISSUE THREAD

**Issue by FriedrichKoenig** [ArduinoHannover/DBAPI#5]
Hallo Zusammen,
Ich frage mich welche Funktion die target variable in getStationBoard hat und wie sie benutzt wird. Wenn ich den Namen eines Endbahnhofes (bzw. Haltestelle auf dem Weg dorthin) eingebe, bekomme ich den gleichen Output wie ohne eine Target variable. 
Konkret: 
`DBdeparr* da = db.getStationBoard("dep",station->stationId, "Augsburg-Hochzoll", NULL, NULL, 10, PROD_IR | PROD_RE);`

Benutze ich es falsch oder gibt es dort Probleme?

Besten Dank und viele Grüße,
F. König

**Comment by soundstorm** [comment]
Parameter Z= ist dirInput= geworden, müsste jetzt wieder laufen :-)
